os:
  - Visual Studio 2015

configuration:
  - Release

environment:
  CTEST_OUTPUT_ON_FAILURE: 1

build_script:
  # this will be successful
  - md build
  - cd build
  - cmake ..
    -DCMAKE_CXX_FLAGS="-WX"
  # this will fail
  - cd ..
  - md build_
  - cd build_
  - cmake ..
    -DCMAKE_CXX_FLAGS="-WX"
    -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
